config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  get "home/index"

  # sessions
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  # Entra authentication routes
  get "/auth/failure", to: "sessions#failure"
  get "/auth/:provider", to: "sessions#new"
  get "/auth/:provider/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"

  resources :dashboards, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  # TODO
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      session[:user_id]
    end

    def require_authentication
      authenticated? || request_authentication
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to sessions_new_path
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  # GET /dashboards or /dashboards.json
  def index
  end

  private
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  allow_unauthenticated_access(only: :index)

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]

  def new
  end

  def create
    logger.info "create with #{params}"
    auth = request.env["omniauth.auth"]
    # could add guard if auth is nil

    user = User.find_or_create_by!(provider: auth["provider"], uid: auth["uid"]) do |u|
      u.first_name = auth["info"]["first_name"]
      u.last_name = auth["info"]["last_name"]
      u.email = auth["info"]["email"]
    end

    session[:user_id] = user.id
    redirect_to root_path, notice: "Signed in #{user.email} successfully"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed out successfully"
  end

  def failure
    msg = "Authentication failed: #{params[:message]}"
    logger.error msg
    redirect_to root_path, alert: msg
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dashboards/index.html.slim
p style="color: green" = notice

h1 
  | Dashboard for
  =< User.find(session[:user_id]).email

p This should only be visible after login

app/views/home/index.html.slim
p style="color: green" = notice
p style="color: red" = alert

h1#home Home

- if session[:user_id]
  p 
    | Welcome, 
    =User.find(session[:user_id]).email 
  = button_to "sign out", logout_path, method: :delete 
- else
  = link_to 'Sign in with Entra ID', "/auth/entra_id"

p= link_to :dashboard, dashboards_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Auth Azure App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>